image: node:latest

variables:
    MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
    MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

##cache:
  ##paths:
    ##- .m2/repository/
    ##- target/
    
stages:
    - build
    - test
    - deploy

build:
    stage: build
    ##before_script:
        ##- yum update
        ##- apt-get install zip unzip
    script:
        ##- mvn $MAVEN_CLI_OPTS compile
        - echo "hello:"
        - zip -r simple-mven-dep.zip $CI_PROJECT_DIR
    only:
        refs: 
            - zip_folder
    ##artifacts:
        ##paths:
            ##- simple-maven-dep.zip

.test:
    image: maven:3.6.3
    stage: test
    script:
        - echo "test"