image: alpine:latest

stages:
    - build

cache:
    paths:
        - artifact_folder/

build:
    stage: build
    script:
        - echo "hello:"
        - ls -lrt ##list all directory
        - ls -l | wc -l ##list number of files
        - ls jil/dev | wc -l ##list number of files in jil folder
        - ls jil/dev ##list all files in the directory
        ##- ls jil/dev | head -n 1 ##find the latest file in particular directory
        - find jil/dev -name "*.jil" | wc -l ##finding number of files with specific extension 
        - find jil/dev -name "*.jil"
        - find jil/qa -name "*.jil" | wc -l
        - find jil/prod -name "*.sh" | wc -l
        - FILES=$(find jil/dev -name "*.jil" | wc -l) ##storing the values in variable 
        - echo "There are $FILES in dev env." 
        - |
            if [ $FILES == 3 ]
            then
                echo "Sunday is the holiday"
            else
                echo "wrong cmd"
            fi
        - | 
            abc="sample1.jil"
            for dirname in $(ls -d jil/dev/*)  ##for loop
            do
                echo "$dirname"
                if cmp -s "$dirname" "jil/dev/$abc"; ##comparing files
                then
                    echo "file found"
                else 
                    echo "file not found"
                fi
            done