image: alpine:latest

stages:
    - build

build:
    stage: build
    before_script:
        - apk update
        - apk add zip
    script:
        - echo "hello:"
        - zip -r simple-mven-dep.zip $CI_PROJECT_DIR/*
    artifacts:
        paths:
            - simple-maven-dep.zip
            - README.md

.test:
    image: maven:3.6.3
    stage: test
    script:
        - echo "test"