image: maven:latest

stages:
    - build

build:
    stage: build
    ##before_script:
        ##- apk update
        ##- apk add zip
    script:
        - echo "hello:"
        - mvn clean install
        ##- ls -lrt
        - zip -r simple-mvn.zip $CI_PROJECT_DIR/*
        ##- ls -lrt
    artifacts:
        paths:
            - simple-mvn.zip
            - README.md

.test:
    image: maven:3.6.3
    stage: test
    script:
        - echo "test"