image: alpine:latest

stages:
    - build

build:
    stage: build
    script:
        - echo "hello:"
        - ls -lrt ##list all directory
        - ls -l | wc -l ##list number of files
        - ls -l | grep -v ^l | wc -l ##list number of files
        - ls jil | wc -l ##list number of files in jil folder