image: alpine:latest

stages:
    - build

before_script:
    - apk update
    - apk add zip

build:
    stage: build
    script:
        ##- echo "hello:"
        ##- ls jil/dev | head -n 1 ##latest files
        ##- ls -lrt ##list all directory
        ##- ls -l | wc -l ##list number of files
        ##- ls jil/dev | wc -l ##list number of files in jil folder
        ##- ls jil/dev ##list all files in the directory
        ##- find jil/dev -name "*.jil" | wc -l ##finding number of files with specific extension 
        ##- find jil/dev -name "*.jil" ##finds and list out the file with .jil extension
        ##- find jil/prod -name "*.sh" | wc -l ##finds the file with .sh... if file not found with .sh extension then it will display as 0
        ##- find jil/dev/* -iname "*.jil" -mtime -1 ## fetch the commited files for past 24hrs 
        ##- find jil/dev/* -maxdepth 1 -mtime -1 ## fetch the commited files for past 24hrs
        ##- find jil/dev/* -iname "*.jil" -mtime 1 ## fetch the commited files for exactly 1day
        ##- FILES=$(find jil/dev -name "*.jil" | wc -l) ##storing the values in variable 
        ##- echo "There are $FILES in dev env." 
        
        ##- |
            ##if [ $FILES == 2 ]
            ##then
                ##echo "Sunday is the holiday"
            ##else
                ##echo "wrong cmd"
            ##fi
        
        ##- | 
            ##abc="sample1.jil"
            ##for dirname in $(ls -d jil/dev/*)  ##listing all files and storing in variable by using for loop
            ##do
                ##echo "$dirname"
                ##if cmp -s "$dirname" "jil/dev/$abc"; ##comparing files (should give the path for the file which has to be compared with)
                ##then
                    ##echo "file found"
                ##else 
                    ##echo "file not found"
                ##fi
            ##done
        
##        - | ## THIS METHOD IS TO FIND THE FILES BY COMPARING
            ##for dirname in $(cat raw.md)  ##read the file and store the values in variable by using for loop
            ##do
                ##echo "$dirname"
                ##for dir in $(ls -d jil/dev/*) ##listing all files and storing in variable by using for loop
                ##do
                    ##echo $dir
                    ##if cmp -s "$dir" "jil/dev/$dirname"; ##comparing files (should give the path for the file which has to be compared with)
                    ##then
                        ##echo "file found"
                        ##echo "*****"
                        ##cp $dir code ##copyig the files from $dir to code directory
                        ##ls code
                        ##echo "*****"
                        ##zip -r arti.zip code/* ##zipping the whole code folder **for zipping only files use cmd -> zip -j arti.zip $dir **  
                    ##else 
                        ##echo "file not found"
                    ##fi
                ##done
            ##done
        
        - | ##THIS METHOD IS TO FIND THE FILES WITHOUT COMPARING... USING "FIND" COMMAND
            for dirname in $(cat raw.md)  
            do
                var=$(find jil/dev -name $dirname)
                zip -j arti.zip $var
            done
    artifacts:
        paths:
            - arti.zip