image: maven:latest

variables:
    MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
    MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/
    
stages:
    - build
    - test
    - deploy

build
    stage: build
    script:
        - mvn $MAVEN_CLI_OPTS compile
    only:
        - master
    artifacts:
        paths:
            - artifact_folder/*
