image: alpine:latest

stages:
    - build

build:
    stage: build
    script:
        - echo "hello:"
        - ls -lrt ##list all directory
        - ls -l | wc -l ##list number of files
        - ls -l | grep -v ^l | wc -l ##list number of files
        - ls jil/dev | wc -l ##list number of files in jil folder
        - find jil/dev -name "*.jil" | wc -l ##finding number of files with specific extension 
        - find jil/dev -name "*.jil" 
        - find jil/qa -name "*.jil" | wc -l
        - find jil/prod -name "*.sh" | wc -l
        - FILES='sudo find jil/dev -name "*.jil" | wc -l' ##storing the values in variable 
        - echo "There are $FILES in dev env." 